#!/usr/bin/python3

import rospy

from rover_main.msg import controllerMap

def control_commands_recievied():
    """Called when new control information is recieived from the operator"""
    pass

def create_node():
    """Starts the node and creates the required data topics"""

    # Create a new network communication node
    rospy.init_node("rover_network_comms", anonymous=True)

    # Create the topic that control information will be sent over
    rospy.Subscriber(name="rover_control_stream",
                     data_class=controllerMap,
                     callback=control_commands_recievied)

   

