#!/usr/bin/python3

import rospy

from rover_main.msg import controllerMap

CONTROLLER_STATE = None

def create_node():
    """Starts the node and creates the required data topics"""

    # Create a new network communication node
    rospy.init_node("rover_network_comms", anonymous=True)

    # Connect to the controller service directly to receive information about the controller state
    rospy.wait_for_service("controller_service")
    controller_service = rospy.ServiceProxy("controller_service", service_class=ControlService, persistent=True)

    # Communication Update Rate
    update_rate = rospy.Rate(250)

    while not rospy.is_shutdown():

        # Update the controller state that the rover has
        try:
            CONTROLLER_STATE = controller_service().controllerState
        except rospy.ServiceException as e:
            print(f"An error ocurred when contacting the service: {e}")
        
        update_rate.sleep()

if __name__ == "__main__":
    create_node()

