#!/usr/bin/python3

import rospy

from rover_main.srv import i2c_comms

if __name__ == "__main__":

    # Create a new node to test the I2C_service
    rospy.init_node("I2C_Tester")

    rospy.wait_for_service("i2c_service")

    try:

        # Create a quick and dirty proxy service
        i2c_service_proxy = rospy.ServiceProxy("i2c_service", i2c_comms)

        # Send a service request
        i2c_response = i2c_service_proxy(1, "dr 10")

        print(i2c_response.returnData)

    except rospy.ServiceException as e:
        rospy.logerr_once("Service call failed: %s"%e)