#!/usr/bin/python3

import rospy

from rover_main.srv import I2C_Service

def init_node():
    rospy.init_node("I2C_Service_Tester")

    rospy.wait_for_service("I2C_Service")
    i2c_service = rospy.ServiceProxy("I2C_Service", service_class=I2C_Service, persistent=True)

    try:
        print(i2c_service(i2c_data=[1,1,6,1], device_address=0, register_id=8).response_data)
    except rospy.ServiceException as e:
        rospy.logfatal(f"An error ocurred when contacting the service: {e}")

if __name__ == "__main__":
    init_node()