# Message to send the state of a general controller

# Digital

# Main Shape Keys
bool Key_X
bool Key_Square
bool Key_Circle
bool Key_Triangle

# Option Buttons
bool Key_Select
bool Key_Start

# D-Pad
bool Dpad_Left
bool Dpad_Right
bool Dpad_Up
bool Dpad_Down

# Bumpers
bool Bumper_Left
bool Bumper_Right

# Joysticks
bool Key_LeftJoystick
bool Key_RightJoystick

# Analog

# Joysticks
float32 Joystick_LeftX
float32 Joystick_LeftY

float32 Joystick_RightX
float32 Joystick_RightY

# Triggers
float32 Trigger_Left
float32 Trigger_Right
