# Array of ints to be sent to the I2C device
int32[] i2c_data

# The device of the I2C address set to recieve this data
int32 device_address
---

# Returns response data (if any) from the device
int32[] response_data