#!/usr/bin/python3

import rospy

from sensor_msgs.msg import NavSatFix
from rover_main.srv import GPS_Service, GPS_ServiceResponse

# Create a 3 length array to store lat, long and altitude
GPS_DATA = [0.0, 0.0, 0.0]

def on_service_contact(data):
    """Response when data is requested from the service"""'
    return GPS_ServiceResponse(positional_data=GPS_DATA)

def subscriber_callback(callback):
    """Called when the NMEA data topic is updated"""
    global GPS_DATA

    # Set the indices manually to the matching pieces of data
    GPS_DATA[0] = callback.latitude
    GPS_DATA[1] = callback.longitude
    GPS_DATA[2] = callback.altitude

def init_node():
    # Start the GPS Service
    rospy.init_node("GPSServiceNode")

    # Subscribe to the location fix topic
    rospy.Subscriber(name="fix"
                     data_class=NavSatFix,
                     callback=subscriber_callback
                     queue_size=10)

    # Create the new service that the GPS data can be read from
    rospy.Service(name="GPSService",
                  service_class=GPS_Service,
                  handler=on_service_contact)

    # Notify the terminal that this new node has be created
    rospy.loginfo(f"{rospy.get_name()} Started...")

    # Create callbacks
    rospy.spin()





